<div class="isotope-item">
				<div class="pix-item">
					<div class="hover-mask" data-background="#42dbcc">
						<a href="[field:picname/]" class="zoom-img"><i class="icon-plus"></i></a>
						<a href="[field:arcurl /]"><i class="icon-info"></i></a>
					</div>
					<a href="[field:arcurl /]"><img src="[field:picname/]" alt="[field:fulltitle/]" class="img-responsive" style="height:320px;" /></a>
				</div>
			</div>