<!-- === BLOG ITEM === -->
	<div class="pix_row row scrollreveal">
	
		<div class="col-lg-6 col-md-6 col-sm-12 col-xs-12">
			<div class="blog-info m[field:global.autoindex/]"> 
				<h5 class="blog-title "><a href="[field:arcurl /]">[field:title/]</a> </h5>
				<div  class="blog-content">
					<p>[field:infos /]</p>
				</div>
				<div class="blog-data">
					<div class="pull-left">[field:pubdate function=MyDate('Y-m-d',@me)'/]</div>
					<div class="pull-right"><a href="[field:arcurl /]">查看详情</a></div>
				</div>   
			</div>
		</div>
		
		<div class="col-lg-6 col-md-6 col-sm-12 col-xs-12">
			<div class="blog-thumb"><a href="[field:arcurl /]">
                       <img src="[field:picname/]" alt="[field:fulltitle/]" height="300">
                                     </a></div>
		</div>
		
	</div>